const NOT_FOUND_CODE = 404;
const BAD_REQUEST_CODE = 400;
const SERVER_ERROR_CODE = 500;
const UNAUTHORIZED_ERROR_CODE = 401;

module.exports = {
  NOT_FOUND_CODE, BAD_REQUEST_CODE, SERVER_ERROR_CODE, UNAUTHORIZED_ERROR_CODE,
};
